/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { CodePieceCreateDTO, CodePieceDTO, CodePieceUpdateDTO } from '../models/index'
import {
	CodePieceCreateDTOFromJSON,
	CodePieceCreateDTOToJSON,
	CodePieceDTOFromJSON,
	CodePieceDTOToJSON,
	CodePieceUpdateDTOFromJSON,
	CodePieceUpdateDTOToJSON,
} from '../models/index'

export interface CreateCodePieceRequest {
	codePieceCreateDTO: CodePieceCreateDTO
}

export interface DeleteCodePieceRequest {
	sourcePostSlug: string
}

export interface UpdateCodePieceRequest {
	sourcePostSlug: string
	codePieceUpdateDTO: CodePieceUpdateDTO
}

/**
 *
 */
export class CodePieceControllerApi extends runtime.BaseAPI {
	/**
	 */
	async createCodePieceRaw(
		requestParameters: CreateCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<CodePieceDTO>> {
		if (requestParameters['codePieceCreateDTO'] == null) {
			throw new runtime.RequiredError(
				'codePieceCreateDTO',
				'Required parameter "codePieceCreateDTO" was null or undefined when calling createCodePiece().'
			)
		}

		const queryParameters: any = {}

		const headerParameters: runtime.HTTPHeaders = {}

		headerParameters['Content-Type'] = 'application/json'

		let urlPath = `/code-pieces`

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: CodePieceCreateDTOToJSON(requestParameters['codePieceCreateDTO']),
			},
			initOverrides
		)

		return new runtime.JSONApiResponse(response, (jsonValue) => CodePieceDTOFromJSON(jsonValue))
	}

	/**
	 */
	async createCodePiece(
		requestParameters: CreateCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<CodePieceDTO> {
		const response = await this.createCodePieceRaw(requestParameters, initOverrides)
		return await response.value()
	}

	/**
	 */
	async deleteCodePieceRaw(
		requestParameters: DeleteCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters['sourcePostSlug'] == null) {
			throw new runtime.RequiredError(
				'sourcePostSlug',
				'Required parameter "sourcePostSlug" was null or undefined when calling deleteCodePiece().'
			)
		}

		const queryParameters: any = {}

		const headerParameters: runtime.HTTPHeaders = {}

		let urlPath = `/code-pieces/{sourcePostSlug}`
		urlPath = urlPath.replace(
			`{${'sourcePostSlug'}}`,
			encodeURIComponent(String(requestParameters['sourcePostSlug']))
		)

		const response = await this.request(
			{
				path: urlPath,
				method: 'DELETE',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides
		)

		return new runtime.VoidApiResponse(response)
	}

	/**
	 */
	async deleteCodePiece(
		requestParameters: DeleteCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<void> {
		await this.deleteCodePieceRaw(requestParameters, initOverrides)
	}

	/**
	 */
	async getUserCodePiecesRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<Array<CodePieceDTO>>> {
		const queryParameters: any = {}

		const headerParameters: runtime.HTTPHeaders = {}

		let urlPath = `/code-pieces/me`

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides
		)

		return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CodePieceDTOFromJSON))
	}

	/**
	 */
	async getUserCodePieces(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<Array<CodePieceDTO>> {
		const response = await this.getUserCodePiecesRaw(initOverrides)
		return await response.value()
	}

	/**
	 */
	async updateCodePieceRaw(
		requestParameters: UpdateCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<CodePieceDTO>> {
		if (requestParameters['sourcePostSlug'] == null) {
			throw new runtime.RequiredError(
				'sourcePostSlug',
				'Required parameter "sourcePostSlug" was null or undefined when calling updateCodePiece().'
			)
		}

		if (requestParameters['codePieceUpdateDTO'] == null) {
			throw new runtime.RequiredError(
				'codePieceUpdateDTO',
				'Required parameter "codePieceUpdateDTO" was null or undefined when calling updateCodePiece().'
			)
		}

		const queryParameters: any = {}

		const headerParameters: runtime.HTTPHeaders = {}

		headerParameters['Content-Type'] = 'application/json'

		let urlPath = `/code-pieces/{sourcePostSlug}`
		urlPath = urlPath.replace(
			`{${'sourcePostSlug'}}`,
			encodeURIComponent(String(requestParameters['sourcePostSlug']))
		)

		const response = await this.request(
			{
				path: urlPath,
				method: 'PUT',
				headers: headerParameters,
				query: queryParameters,
				body: CodePieceUpdateDTOToJSON(requestParameters['codePieceUpdateDTO']),
			},
			initOverrides
		)

		return new runtime.JSONApiResponse(response, (jsonValue) => CodePieceDTOFromJSON(jsonValue))
	}

	/**
	 */
	async updateCodePiece(
		requestParameters: UpdateCodePieceRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<CodePieceDTO> {
		const response = await this.updateCodePieceRaw(requestParameters, initOverrides)
		return await response.value()
	}
}
