/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CodePieceCreateDTO
 */
export interface CodePieceCreateDTO {
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	code?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	language?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	title?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	sourcePostSlug?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	exerciseContext?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceCreateDTO
	 */
	solutionCode?: string
}

/**
 * Check if a given object implements the CodePieceCreateDTO interface.
 */
export function instanceOfCodePieceCreateDTO(value: object): value is CodePieceCreateDTO {
	return true
}

export function CodePieceCreateDTOFromJSON(json: any): CodePieceCreateDTO {
	return CodePieceCreateDTOFromJSONTyped(json, false)
}

export function CodePieceCreateDTOFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CodePieceCreateDTO {
	if (json == null) {
		return json
	}
	return {
		code: json['code'] == null ? undefined : json['code'],
		language: json['language'] == null ? undefined : json['language'],
		title: json['title'] == null ? undefined : json['title'],
		sourcePostSlug: json['sourcePostSlug'] == null ? undefined : json['sourcePostSlug'],
		exerciseContext: json['exerciseContext'] == null ? undefined : json['exerciseContext'],
		solutionCode: json['solutionCode'] == null ? undefined : json['solutionCode'],
	}
}

export function CodePieceCreateDTOToJSON(json: any): CodePieceCreateDTO {
	return CodePieceCreateDTOToJSONTyped(json, false)
}

export function CodePieceCreateDTOToJSONTyped(
	value?: CodePieceCreateDTO | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value
	}

	return {
		code: value['code'],
		language: value['language'],
		title: value['title'],
		sourcePostSlug: value['sourcePostSlug'],
		exerciseContext: value['exerciseContext'],
		solutionCode: value['solutionCode'],
	}
}
