/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CodePieceUpdateDTO
 */
export interface CodePieceUpdateDTO {
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceUpdateDTO
	 */
	code?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceUpdateDTO
	 */
	title?: string
	/**
	 *
	 * @type {boolean}
	 * @memberof CodePieceUpdateDTO
	 */
	isSolved?: boolean
}

/**
 * Check if a given object implements the CodePieceUpdateDTO interface.
 */
export function instanceOfCodePieceUpdateDTO(value: object): value is CodePieceUpdateDTO {
	return true
}

export function CodePieceUpdateDTOFromJSON(json: any): CodePieceUpdateDTO {
	return CodePieceUpdateDTOFromJSONTyped(json, false)
}

export function CodePieceUpdateDTOFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CodePieceUpdateDTO {
	if (json == null) {
		return json
	}
	return {
		code: json['code'] == null ? undefined : json['code'],
		title: json['title'] == null ? undefined : json['title'],
		isSolved: json['isSolved'] == null ? undefined : json['isSolved'],
	}
}

export function CodePieceUpdateDTOToJSON(json: any): CodePieceUpdateDTO {
	return CodePieceUpdateDTOToJSONTyped(json, false)
}

export function CodePieceUpdateDTOToJSONTyped(
	value?: CodePieceUpdateDTO | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value
	}

	return {
		code: value['code'],
		title: value['title'],
		isSolved: value['isSolved'],
	}
}
