/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CodePieceDTO
 */
export interface CodePieceDTO {
	/**
	 *
	 * @type {number}
	 * @memberof CodePieceDTO
	 */
	id?: number
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceDTO
	 */
	code?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceDTO
	 */
	language?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceDTO
	 */
	title?: string
	/**
	 *
	 * @type {string}
	 * @memberof CodePieceDTO
	 */
	sourcePostSlug?: string
	/**
	 *
	 * @type {boolean}
	 * @memberof CodePieceDTO
	 */
	isSolved?: boolean
	/**
	 *
	 * @type {Date}
	 * @memberof CodePieceDTO
	 */
	createdAt?: Date
	/**
	 *
	 * @type {Date}
	 * @memberof CodePieceDTO
	 */
	updatedAt?: Date
}

/**
 * Check if a given object implements the CodePieceDTO interface.
 */
export function instanceOfCodePieceDTO(value: object): value is CodePieceDTO {
	return true
}

export function CodePieceDTOFromJSON(json: any): CodePieceDTO {
	return CodePieceDTOFromJSONTyped(json, false)
}

export function CodePieceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodePieceDTO {
	if (json == null) {
		return json
	}
	return {
		id: json['id'] == null ? undefined : json['id'],
		code: json['code'] == null ? undefined : json['code'],
		language: json['language'] == null ? undefined : json['language'],
		title: json['title'] == null ? undefined : json['title'],
		sourcePostSlug: json['sourcePostSlug'] == null ? undefined : json['sourcePostSlug'],
		isSolved: json['isSolved'] == null ? undefined : json['isSolved'],
		createdAt: json['createdAt'] == null ? undefined : new Date(json['createdAt']),
		updatedAt: json['updatedAt'] == null ? undefined : new Date(json['updatedAt']),
	}
}

export function CodePieceDTOToJSON(json: any): CodePieceDTO {
	return CodePieceDTOToJSONTyped(json, false)
}

export function CodePieceDTOToJSONTyped(
	value?: CodePieceDTO | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value
	}

	return {
		id: value['id'],
		code: value['code'],
		language: value['language'],
		title: value['title'],
		sourcePostSlug: value['sourcePostSlug'],
		isSolved: value['isSolved'],
		createdAt: value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
		updatedAt: value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
	}
}
